/*
 * This source file was generated by the Gradle 'init' task
 */
package dslinkedlist;

public class App {
    // public String getGreeting() {
    //     return "Hello World!";


    public static void main(String[] args) {
        JunaLinkedList linked = new JunaLinkedList();

        linked.insertAtBeginning(20);
        linked.insertAtBeginning(10);
        linked.display();

        linked.insertAtEnd(30);
        linked.insertAtEnd(40);
        linked.display();

        System.out.println(linked.search(30));

        linked.delete(20);
        linked.display();

        linked.delete(10);
        linked.display();

        System.out.println(linked.search(100));
    }
}

